wifi:
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nilan Fallback Hotspot"
    password: !secret wifi_password

# Enable the captive portal for inital WiFi setup
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esphome:
  name: nilan
  platform: ESP32
  board: esp-wrover-kit
  
  includes:
    - nilan/src/temp_sensors.h
#    - nilan/src/temp_sensors.cpp

  on_boot:
    priority: -10
    then:
    - wait_until:
        api.connected:
    - logger.log: API is connected!

# Setup uart, required by modbus
uart:
  id: uart_nilan
  baud_rate: 19200
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  rx_pin: GPIO16
  tx_pin: GPIO17

# Enable modbus
modbus:
  id: modbus_nilan
  uart_id: uart_nilan

sensor:
- platform: custom
  lambda: |-
    auto temp_sensors = new TempSensors(modbus_nilan);
    App.register_component(temp_sensors);
    return {temp_sensors->controller_temp_sensor_, temp_sensors->exhaust_temp_sensor_, temp_sensors->outlet_temp_sensor_, temp_sensors->inlet_temp_sensor_, temp_sensors->outdoor_temp_sensor_};

  sensors:
  - name: "Nilan Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 2
    id: controller_temperature
  - name: "Exhaust Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 2
    id: exhaust_temperature
  - name: "Outlet Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 2
    id: outlet_temperature
  - name: "Inlet Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 2
    id: inlet_temperature
  - name: "Outdoor Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 2
    id: outdoor_temperature